Desktop Version
nouman17610/figma-template01 pull request #4
Opened 2023-07-13 14:06 UTC by nouman17610

I implemented the following areas in desktop version

- Header section
- Work section
- About section
- Contact form

2023-07-13 15:53 UTC, Munsa1 requested changes
Hi @nouman17610, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Good UI Design :heavy_check_mark: 
Descriptive PR Description :heavy_check_mark: 
Good Commit Messages :heavy_check_mark: 
Media Queries Used Correctly ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 15:53 UTC, Munsa1 commented on README.md
>    <!-- You are encouraged to replace this logo with your own! Otherwise you can also remove it. -->
- [ ] Good job creating a professional readme file, however, kindly remove **ALL**  comments that are not relevanto to the readme file for a more professional documentation.

![image](https://github.com/nouman17610/figma-template01/assets/81932478/0f4ce507-df02-4e3c-b494-5f6f3ffc6dc6)
![image](https://github.com/nouman17610/figma-template01/assets/81932478/935996df-7b50-4f27-9a74-d4a8c126fcaa)
![image](https://github.com/nouman17610/figma-template01/assets/81932478/a365fd67-209f-4b52-99a3-c8f56df63948)
![image](https://github.com/nouman17610/figma-template01/assets/81932478/5a9ba1cf-22b4-4e24-b410-79d54d90de8b)
![image](https://github.com/nouman17610/figma-template01/assets/81932478/7e163575-cd44-4587-a46c-92594b02cccb)
![image](https://github.com/nouman17610/figma-template01/assets/81932478/090017d5-8f3c-49da-a242-37ccb8324431)

2023-07-13 15:53 UTC, Munsa1 commented on README.md
>  </div>
- [ ] Kindly remove the broken links in your `table of contents` that lead the user to sections which do not exist.

e.g
- Kindly remove the `Live Demo` link as the readme file does not have a `Live Demo` section
![image](https://github.com/nouman17610/figma-template01/assets/81932478/12e22095-e91b-48a9-848c-99949a2a673f)

- Kindly remove the `FAQ` section as well as the FAQ section does not exist as well
![image](https://github.com/nouman17610/figma-template01/assets/81932478/e5b3b391-d581-42f6-8057-64b48c1c9bba)

2023-07-13 15:53 UTC, Munsa1 commented on index.html
> +        </ul>
- [ ] Kindly note that it is a requirement that the implementation of the desktop version should not break the design of the mobile version. Kindly fix your mobile versionto match the given design

### Your design


Introductory section

![image](https://github.com/nouman17610/figma-template01/assets/81932478/4d35bc62-815a-4c0f-818a-a68a6f589461)

Works Section

![image](https://github.com/nouman17610/figma-template01/assets/81932478/cefbe153-5fe3-4315-a56e-95e75fef567c)

About Section

![image](https://github.com/nouman17610/figma-template01/assets/81932478/9fb6207f-f1f6-4852-87a6-2fa1723ff21b)


### Given layout

Inroduction

![image](https://github.com/nouman17610/figma-template01/assets/81932478/517adf34-b37d-48ed-b505-5396ee487963)

Works Section

![image](https://github.com/nouman17610/figma-template01/assets/81932478/bb5d494d-bce4-4925-8760-53d9cf92a414)

About Section

![image](https://github.com/nouman17610/figma-template01/assets/81932478/e259700f-ab3c-4228-acad-bb908b76a6be)

![image](https://github.com/nouman17610/figma-template01/assets/81932478/34a47913-83c4-40b5-a4d8-9e4213427c90)

2023-07-13 15:53 UTC, Munsa1 commented on index.html
> +            <p>CANOPY</p>
- [ ] Kindly ensure this tag has the same color and font-weight as the given design as this is a requirement

Your design
![image](https://github.com/nouman17610/figma-template01/assets/81932478/e085044d-8092-4197-a4ac-f6be8dd53aa7)

Given design
![image](https://github.com/nouman17610/figma-template01/assets/81932478/ba10d8e0-1eff-499a-9e41-a45110934b26)

### Note this applies to all the cards

2023-07-13 15:53 UTC, Munsa1 commented on index.html
>      <section class="work-area">
- [ ] The second and last cards from the top in the `works` section have their card images to the right and the card description to the right. Kindly implement this as well

Given design
![image](https://github.com/nouman17610/figma-template01/assets/81932478/47779f0f-9120-4f05-93bf-ffdf48925a79)

Your design
![image](https://github.com/nouman17610/figma-template01/assets/81932478/ceecae1a-e963-4a2b-86c1-d8a3b4036ccd)

### Design for the last card from the top

Given design
![image](https://github.com/nouman17610/figma-template01/assets/81932478/71f16a06-d881-43b3-a3e6-5c681173767b)

Your design
![image](https://github.com/nouman17610/figma-template01/assets/81932478/1c66fedb-e223-47b5-b2ca-e5e1dc5542b6)

### Note 🔴 
Kindly change your text to reflect the text in each card for a design that is more close to the Figma template

2023-07-14 14:06 UTC, tugsem requested changes
## STATUS: REQUIRED CHANGES ♻️
Hello @nouman17610 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif)

 ## Highlights 🚀
✔️Good job on clearing readme and fixing the mobile version of the app
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 14:06 UTC, tugsem commented on style.css
> +@media (min-width: 768px) {
-  [ ] Good job on fixing the layout of the mobile version as requested by the reviewer, however now your app on screens **768px** in width, seems like overlapping some text to each other. Kindly fix it for all of the cards and make sure to check screen sizes from 768px to upper and have the same layout.
![image](https://github.com/nouman17610/figma-template01/assets/91486791/43089e5a-e177-4572-9a3a-6c9a26388ac2)

2023-07-14 15:21 UTC, Munsa1 approved these changes
Hi @nouman17610, 
![Approved 1](https://github.com/nouman17610/figma-template01/assets/81932478/09dffbee-70b9-4e7f-a124-701129548e01)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Fixed Overlap As Requested By Previous Reviewer :heavy_check_mark: 
Achieved A Good Responsive Design :heavy_check_mark: 
Good Commit Messages :heavy_check_mark: 

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 15:27 UTC, merged