Toggle menu
nouman17610/figma-template01 pull request #7
Opened 2023-07-25 10:51 UTC by nouman17610

I implemented the following in the mobile menu
- Clickable toggle button
- Menu list on mobile menu
- Clickable menu items
- Removal toggle menu by clicking on the cross

2023-07-25 11:40 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/4WFFDhSWjNfa63W8sW/giphy.gif)


# Hi @nouman17610 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 11:40 UTC, AbelG101 commented on style.css
> +  }
- [ ] Kindly make sure your implementation of the design matches the one shown in the Figma design as I noticed some discrepancies in the design of the mobile menu. As you can see in the Figma design below the menu links have a bolder font-weight with some spacing to the left and there's a blur effect on the background the background color also has a darker tone to it so I'd suggest you update your design to match these properties.
- Figma design:
  ![image](https://github.com/jerymey/Portfolio-setup/assets/104968236/a96e8d8a-0550-4f3e-8bec-05ef0df56b5d)
- Your design:
  ![image](https://github.com/nouman17610/figma-template01/assets/104968236/dcfe3c7e-fbdd-4b2d-b5c0-806919b2a20f)

2023-07-25 11:40 UTC, AbelG101 commented on template01.js
> +});
- [ ] As part of the project requirements, it's important that when a user clicks or taps any of the mobile menu options, the corresponding section of the page is displayed. However, I noticed that this implementation has been missed. Additionally, please make sure that the mobile menu closes automatically after the user clicks on any of the links. 
- [ ] Furthermore, I came across a bug on the menu. After clicking the cross icon, the mobile menu fails to open when the hamburger icon is clicked, which leads to a poor user experience. It would be great if you could resolve this issue as soon as possible to ensure a seamless mobile experience for our users. Thank you for your hard work! 💪
    - Here's how it behaves:
      ![firefox_K9vSrksRfV](https://github.com/nouman17610/figma-template01/assets/104968236/d7ac124d-72d9-413b-b2ea-86e91c3337b5)

2023-07-26 10:35 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @nouman17610 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
Correct use of GitHub Flow ✔
All linter checks are passing ✔
Descriptive PR title with a great summary ✔ 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 10:35 UTC, iambenkis commented on template01.js
> +});
- [ ] As requested by the previous CR and even as it stated in the project requirement 👍 , the hamburger button should work continually and not once, the fact is your hamburger button is working only once 👍 , Kindly improve that.

**[Debugging note]**
After checking your code, Kindly re-check the role of the `hide` class in your project on line `14`. 😄

2023-07-26 10:50 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @nouman17610, and @enocol👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 11:03 UTC, merged